"""empty message

Revision ID: 3e1198f65a99
Revises: 
Create Date: 2019-12-22 22:26:16.763550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e1198f65a99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('absoluteUrl', sa.String(length=512), nullable=True),
    sa.Column('imageUrl', sa.String(length=1024), nullable=True),
    sa.Column('locationId', sa.Integer(), nullable=True),
    sa.Column('accommodationCategory', sa.String(length=32), nullable=True),
    sa.Column('ratingCounts_serialized', sa.String(length=64), nullable=True),
    sa.Column('languageCounts_serialized', sa.String(length=128), nullable=True),
    sa.Column('additionalRatings_serialized', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('absoluteUrl'),
    sa.UniqueConstraint('imageUrl'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=10000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unigram',
    sa.Column('text', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('text')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('absoluteUrl', sa.String(length=512), nullable=True),
    sa.Column('createdDate', sa.String(length=32), nullable=True),
    sa.Column('stayDate', sa.String(length=32), nullable=True),
    sa.Column('publishedDate', sa.String(length=32), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('user_hometownId', sa.Integer(), nullable=True),
    sa.Column('user_hometownName', sa.String(length=256), nullable=True),
    sa.Column('title', sa.String(length=2048), nullable=True),
    sa.Column('text', sa.String(length=100000), nullable=True),
    sa.Column('spacyText', sa.String(length=500000), nullable=True),
    sa.Column('hotelId', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['hotelId'], ['hotel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_absoluteUrl'), 'review', ['absoluteUrl'], unique=True)
    op.create_table('tags',
    sa.Column('unigram_text', sa.String(length=64), nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentence.id'], ),
    sa.ForeignKeyConstraint(['unigram_text'], ['unigram.text'], ),
    sa.PrimaryKeyConstraint('unigram_text', 'sentence_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_index(op.f('ix_review_absoluteUrl'), table_name='review')
    op.drop_table('review')
    op.drop_table('unigram')
    op.drop_table('sentence')
    op.drop_table('hotel')
    # ### end Alembic commands ###
